name: nearest_technician_app
description: Nearest technician demo with Firebase integration
publish_to: 'none'
version: 1.0.5+7

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  http: ^1.6.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  upgrader: ^13.2.0
  firebase_auth: ^6.5.1
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/certificates/isrg_root_x1.pem
